default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: demo_development
  username: root
  password: hrhk
  host: localhost

production:
  <<: *default
  database: demo_production
  username: 
  password: 
  host: 
