# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 562fa7e99ef8dec591bf8393a6f54b8c60ecf4664e1121864a4e0fb4100552310d1762c08f49a95275412189133eefa97c0f66b5c39f4447c8f684e7f62c58a0

test:
  secret_key_base: dd4426e66ab6a80352cbb5ea3570c367fa091a8dbea52a35548995dbb48700ce6dc6f5bd0546e291194e54c3f1fb2ed993818d26d5a42fb8d899dbc1c3cf3262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
